version: '3'

volumes:
  javaserverdata1:

networks:
  javaservernet1:

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - javaserverdata1:/data/db
    command: --smallfiles
    networks:
      - javaservernet1
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/javaserver-0.1.0.jar
    image: mrmcgrewx/javaserver:latest
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - javaservernet1
